language: node_js
node_js:
    - "node" # use latest stable nodejs version

cache:
    npm: false

before_script:

script:
    #- npm run coverage # jest test with coverage flag does coverage too
    - npm test

after_script:
    ##- "cat coverage/lcov.info | ./node_modules/.bin/coveralls" # sends the coverage report to coveralls
#env:
#       NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
